#! /bin/bash
# Author : Matt Flax <flatmax@flatmax.org>
# Date : Nov 2018

if [ $# -lt 1 ]; then
  echo usage :
  me=`basename "$0"`
  echo "     " $me path.to.buildroot.neo4
  echo for example :
  echo "     " $me /home/flatmax.unencrypted/buildroot.rockchip
else
  DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

  CUSTOM_PATH=$DIR
  BR_REPO_PATH=$1
  BR_DEFCONFIG=neo4_defconfig
  BR_CUSTOM_DEFCONFIG=neo4_custom_defconfig
  BR_REF_DEFCONFIG=rockchip_rk3399_defconfig

  if [ ! -d "$BR_REPO_PATH" ]; then
  	echo Can\'t find the directory $BR_REPO_PATH please correct the bash script.
  	return;
  fi
  if [ ! -d "$CUSTOM_PATH" ]; then
  	echo Can\'t find the directory $CUSTOM_PATH please correct the bash script.
  	return;
  fi

  if [ ! -e $BR_REPO_PATH/configs/$BR_REF_DEFCONFIG ]; then
    echo can\'t find the file $BR_REPO_PATH/configs/$BR_REF_DEFCONFIG
    echo please fix this script
    return;
  fi
  if [ ! -e $BR_REPO_PATH/configs/rockchip ]; then
    echo can\'t find the directory $BR_REPO_PATH/configs/rockchip
    echo please fix this script
    return;
  fi
  if [ ! -e $CUSTOM_PATH/configs/$BR_CUSTOM_DEFCONFIG ]; then
  	echo can\'t find the file $CUSTOM_PATH/configs/$BR_CUSTOM_DEFCONFIG
  	echo please fix this script
  	return;
  fi

  # generate the buildroot config file
  echo \#autogenerated do not edit, put changes in configs/neo4_custom_defconfig > $CUSTOM_PATH/configs/$BR_DEFCONFIG
  cat $BR_REPO_PATH/configs/$BR_REF_DEFCONFIG >> $CUSTOM_PATH/configs/$BR_DEFCONFIG
  cat $CUSTOM_PATH/configs/$BR_CUSTOM_DEFCONFIG >> $CUSTOM_PATH/configs/$BR_DEFCONFIG
  ln -s $BR_REPO_PATH/configs/rockchip $CUSTOM_PATH/configs/

  cp -a $BR_REPO_PATH/board/rockchip/rk3399/fs-overlay-64/* $CUSTOM_PATH/overlays

  cd $1
  make BR2_EXTERNAL=$CUSTOM_PATH $BR_DEFCONFIG
fi
