#!/bin/sh

case "$1" in
    start)
        echo "Starting weston"
        . /usr/bin/startWeston.sh
        chown root.video /dev/mali0
        chmod g+rw /dev/mali0
        ;;

    stop)
        echo "Stopping weston"
        . /usr/bin/stopWeston.sh
        ;;

    *)
        echo "Usage: $0 start"
        exit 1
        ;;
esac

exit $?
